import React from "react";
import Grid from "@mui/material/Grid";
import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import axios from "axios";
import CircularProgress from "@mui/material/CircularProgress";
function Showresult() {
  let navigate = useNavigate();

  const [isLoading, setisLoading] = useState(false);

  const { state } = useLocation();
  console.log("its state", state.text);

  const [results, setResults] = useState("");

  const Askserc = () => {
    let path = `/`;
    navigate(path);
  };
  useEffect(() => {
    hitAPi();
  }, []);

  async function hitAPi() {
    setisLoading(true);
    const { data } = await axios.post("https://gpt.encodersoft.co/ask", {
      query: state.text,
    });
    console.log(data);

    setResults(data.data);
    setisLoading(false);
  }
  return (
    <>
      <Grid container spacing={2}>
        <Grid item xs={12}>
          <div className="flex justify-between">
            <img
              src={require("assets/image/Bayleyimage.png")}
              className="h-24 ml-8"
              alt=""
            />
            <h3 className="text-3xl font-bold mr-6 mt-5">Bayley Al</h3>
          </div>
        </Grid>
      </Grid>

      {/* <div className='flex justify-between mt-3'>
        {/* <h3 className='text-3xl font-bold ml-6'>Bayley</h3> */}

      {/* </div> */}
      <hr className="border-t-1 border-black  w-full" />

      <Grid container spacing={0}>
        <Grid
          item
          lg={2}
          xs={4}
          sm={3}
          md={3}
          className=" bal-stylin-wrap-side"
        >
          <div className=" bayl-col-styl-show bg-gradiant h-full xs:w-full ">
            <div className="flex">
              <button
                onClick={Askserc}
                className="flex btn-bal-styles mt-4 ml-4 border-2 bg-white text-purple-500 py-2 px-8 rounded-md"
              >
                <i class="fal fa-plus mr-4"></i>
                <p className="  text-wrap-styling">New Chat</p>
              </button>
            </div>
            <button className="flex btn-bal-styl mt-4 ml-4 border-2 bg-white text-purple-500 px-4 py-2 rounded-md">
              <i class="fas fa-comment-dots mt-1 mr-2"></i>
              <p className="text-wrap-styl">How Do I Repl</p>
            </button>
          </div>
        </Grid>
        <Grid item lg={10} xs={8} sm={9} md={9}>
          <div className="">
            <div className="flex justify-center mt-3">
              <img
                src="https://img.freepik.com/free-photo/robot-doing-peace-sign_1048-3527.jpg?w=360&t=st=1673020949~exp=1673021549~hmac=9a3857a5c3d1877e0acedab50f95c5d0e2b100904f45ec51ea753f51dd0c7bc4"
                className="bal-imag-styl h-36"
              />
              <h3 className="text-6xl font-bold mt-7 bal-text-styl">
                Ask Bayley
              </h3>
            </div>
            <div className=" wrap-bal-txt">
              <div className=" styl-bal-desc">
                <p className="resp-text-styl italic flex justify-center">
                  **Disclaimer - All responses are generated by Al data sets and
                  not always exact answers
                </p>
              </div>
            </div>
            <hr className="border-2 border-#F2F2F2" />
            <div className="flex justify-center mt-5">
              <i class="fas fa-user-circle text-purple-500 text-3xl icon-styl"></i>

              <p className="ml-4 show-txt-styl">{state.text}</p>
            </div>
            <br />
            <div className="border-2 border-#F2F2F2 bg-gray-200 h-full  w-full ">
              <div className="flex">
                <img
                  src="https://img.freepik.com/free-photo/robot-doing-peace-sign_1048-3527.jpg?w=360&t=st=1673020949~exp=1673021549~hmac=9a3857a5c3d1877e0acedab50f95c5d0e2b100904f45ec51ea753f51dd0c7bc4"
                  className="bal-imag-styl h-16 ml-6 mt-3"
                />
                <p className="mt-7 ml-5 text-show-wrap">
                  {results}

                  {isLoading ? <CircularProgress /> : null}
                </p>
                <br></br>
                <br></br> <br></br> <br></br> <br></br>
                <br></br> <br></br> <br></br> <br></br>
                <br></br> <br></br> <br></br> <br></br>
                <br></br> <br></br> <br></br> <br></br>
              </div>
              {/* <div className="ml-24 list-show-wrap">
                <li>Lug wrench</li>
                <li>Jack stads</li>
                <li>Hudraulic jack</li>
                <li>Wheel chocks(optional,but recommended)</li>
                <li>Brake caliper tool(or a large C-clamp)</li>
                <li>4-6 inch C-clamp</li>
                <li>Pair of pilers</li>
                <li>Wire brush</li>
                <li>Brake cleaner</li>
                <li>Thin-walled 12-point socket</li>
                <li>Torque wrench</li>
                <li>Shop rags or paper towels</li>
                <li>Gloves(optional,but recommended)</li>
              </div>
              <p className="lg:ml-24 mt-6  text-show-wraping">
                Here are the general steps for replacing the brake pads:
              </p>
              <ul className=" lg:ml-24 list-styl-show-wrap">
                <li>
                  1. Chock the wheels on the oposite side of the car from the
                  wheel you are working on. This will help to keep the <br />{" "}
                  car from rolling while it's on the jack stands.
                </li>
                <li>
                  2.Locate the hudraulic jack points on your car and use the
                  hadraulic jack to lift the car off the ground.Make sure <br />{" "}
                  the car is stable and secure on the jack stands before you get
                  under the car
                </li>
                <li>3.Remove the lug nuts and take the wheel off.</li>
              </ul> */}
            </div>
          </div>
        </Grid>
      </Grid>
    </>
  );
}

export default Showresult;
